"""add_is_harvest_ready_to_farms

Revision ID: 046a6438fa2f
Revises: 7072ef129e8e
Create Date: 2026-03-27 00:59:23.591335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '046a6438fa2f'
down_revision: Union[str, Sequence[str], None] = '7072ef129e8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crop_references', 'cost_per_hectare_max')
    op.drop_column('crop_references', 'market_price_min')
    op.drop_column('crop_references', 'market_price_max')
    op.drop_column('crop_references', 'cost_per_hectare_min')
    # Step 1: Add column as nullable so existing rows don't violate NOT NULL
    op.add_column('farms', sa.Column('is_harvest_ready', sa.Boolean(), nullable=True))
    # Step 2: Backfill existing rows with False
    op.execute('UPDATE farms SET is_harvest_ready = FALSE WHERE is_harvest_ready IS NULL')
    # Step 3: Enforce NOT NULL now that all rows have a value
    op.alter_column('farms', 'is_harvest_ready', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farms', 'is_harvest_ready')
    op.add_column('crop_references', sa.Column('cost_per_hectare_min', sa.INTEGER(), server_default=sa.text('100000'), autoincrement=False, nullable=False))
    op.add_column('crop_references', sa.Column('market_price_max', sa.INTEGER(), server_default=sa.text('500000'), autoincrement=False, nullable=False))
    op.add_column('crop_references', sa.Column('market_price_min', sa.INTEGER(), server_default=sa.text('50000'), autoincrement=False, nullable=False))
    op.add_column('crop_references', sa.Column('cost_per_hectare_max', sa.INTEGER(), server_default=sa.text('500000'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
