"""add verified_at to harvest reports

Revision ID: 07a1c0cf6bb9
Revises: 046a6438fa2f
Create Date: 2026-03-27 07:23:03.722221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '07a1c0cf6bb9'
down_revision: Union[str, Sequence[str], None] = '046a6438fa2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('harvest_reports', sa.Column('verified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('harvest_reports', 'verified_at')
    # ### end Alembic commands ###
