"""Add admin and proof fields to Farm and Milestone models

Revision ID: 23bd9f34a180
Revises: 9f05b30dad35
Create Date: 2026-03-25 11:04:37.285327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '23bd9f34a180'
down_revision: Union[str, Sequence[str], None] = '9f05b30dad35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farms', sa.Column('confirmed_sales_amount', sa.Integer(), nullable=True))
    op.add_column('milestones', sa.Column('proof_photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('milestones', sa.Column('proof_latitude', sa.Float(), nullable=True))
    op.add_column('milestones', sa.Column('proof_longitude', sa.Float(), nullable=True))
    op.add_column('milestones', sa.Column('gps_distance_km', sa.Float(), nullable=True))
    op.add_column('milestones', sa.Column('gps_flag', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('milestones', sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('milestones', 'submitted_at')
    op.drop_column('milestones', 'gps_flag')
    op.drop_column('milestones', 'gps_distance_km')
    op.drop_column('milestones', 'proof_longitude')
    op.drop_column('milestones', 'proof_latitude')
    op.drop_column('milestones', 'proof_photo_url')
    op.drop_column('farms', 'confirmed_sales_amount')
    # ### end Alembic commands ###
