"""Add harvest and payout models

Revision ID: 2825f509c783
Revises: 3282b84a0aaa
Create Date: 2026-03-25 18:26:36.373760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '2825f509c783'
down_revision: Union[str, Sequence[str], None] = '3282b84a0aaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('harvest_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('farmer_id', sa.Uuid(), nullable=False),
    sa.Column('actual_yield', sa.Float(), nullable=False),
    sa.Column('total_sales_declared', sa.Integer(), nullable=False),
    sa.Column('harvest_date', sa.Date(), nullable=False),
    sa.Column('buyer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payment_evidence_public_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('admin_confirmed_sales', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'VERIFIED', 'REJECTED', name='harvestreportstatus'), nullable=False),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id')
    )
    op.create_table('payouts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_type', sa.Enum('INVESTOR', 'FARMER', name='recipienttype'), nullable=False),
    sa.Column('investment_id', sa.Uuid(), nullable=True),
    sa.Column('principal_naira', sa.Integer(), nullable=False),
    sa.Column('profit_naira', sa.Integer(), nullable=False),
    sa.Column('total_amount_naira', sa.Integer(), nullable=False),
    sa.Column('interswitch_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('WAITING', 'PROCESSING', 'COMPLETED', 'FAILED', name='payoutstatus'), nullable=False),
    sa.Column('failure_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('initiated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payouts_farm_id'), 'payouts', ['farm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payouts_farm_id'), table_name='payouts')
    op.drop_table('payouts')
    op.drop_table('harvest_reports')
    # ### end Alembic commands ###
