"""added creation of farm logic

Revision ID: 5f2bd5081d2e
Revises: 
Create Date: 2026-03-24 20:40:28.162387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5f2bd5081d2e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farmer_id', sa.Uuid(), nullable=False),
    sa.Column('crop_reference_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('crop_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lga', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('farm_size_ha', sa.Float(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_budget', sa.Integer(), nullable=False),
    sa.Column('amount_raised', sa.Integer(), nullable=False),
    sa.Column('expected_yield', sa.Float(), nullable=False),
    sa.Column('sale_price_per_unit', sa.Integer(), nullable=False),
    sa.Column('return_rate', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('harvest_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'FUNDED', 'COMPLETED', 'PAID_OUT', 'REJECTED', 'DEADLINE_PASSED', 'CANCELLED', name='farmstatus'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_Verified', sa.Boolean(), nullable=False),
    sa.Column('location_photo_public_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('display_photos_public_id', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deadline_passed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('extension_decision_deadline', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('extension_count', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crop_reference_id'], ['crop_references.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farms_crop_reference_id'), 'farms', ['crop_reference_id'], unique=False)
    op.create_index(op.f('ix_farms_farmer_id'), 'farms', ['farmer_id'], unique=False)
    op.create_table('milestones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.Column('expected_week', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('LOCKED', 'PENDING_PROOF', 'UNDER_REVIEW', 'VERIFIED', 'DISBURSED', 'REJECTED', name='milestonestatus'), nullable=False),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milestones_farm_id'), 'milestones', ['farm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_milestones_farm_id'), table_name='milestones')
    op.drop_table('milestones')
    op.drop_index(op.f('ix_farms_farmer_id'), table_name='farms')
    op.drop_index(op.f('ix_farms_crop_reference_id'), table_name='farms')
    op.drop_table('farms')
    # ### end Alembic commands ###
