"""Move milestone proofs to relational Proof model

Revision ID: 6a8fde50b658
Revises: 23bd9f34a180
Create Date: 2026-03-25 12:29:03.387265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6a8fde50b658'
down_revision: Union[str, Sequence[str], None] = '23bd9f34a180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proofs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('milestone_id', sa.Uuid(), nullable=False),
    sa.Column('farmer_id', sa.Uuid(), nullable=False),
    sa.Column('photo_public_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gps_latitude', sa.Float(), nullable=False),
    sa.Column('gps_longitude', sa.Float(), nullable=False),
    sa.Column('gps_accuracy_m', sa.Float(), nullable=True),
    sa.Column('gps_distance_km', sa.Float(), nullable=False),
    sa.Column('gps_flag', sa.Enum('PASS', 'WARNING', 'FAIL', name='gpsflag'), nullable=False),
    sa.Column('gps_flag_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'APPROVED', 'REJECTED', name='proofstatus'), nullable=False),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proofs_milestone_id'), 'proofs', ['milestone_id'], unique=False)
    op.drop_column('milestones', 'proof_longitude')
    op.drop_column('milestones', 'gps_flag')
    op.drop_column('milestones', 'proof_photo_url')
    op.drop_column('milestones', 'proof_latitude')
    op.drop_column('milestones', 'submitted_at')
    op.drop_column('milestones', 'gps_distance_km')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestones', sa.Column('gps_distance_km', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('milestones', sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('milestones', sa.Column('proof_latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('milestones', sa.Column('proof_photo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('milestones', sa.Column('gps_flag', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('milestones', sa.Column('proof_longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_proofs_milestone_id'), table_name='proofs')
    op.drop_table('proofs')
    # ### end Alembic commands ###
