"""refactor_finances_and_farm_location

Revision ID: 7072ef129e8e
Revises: 7827b5de088b
Create Date: 2026-03-26 06:06:05.093820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7072ef129e8e'
down_revision: Union[str, Sequence[str], None] = '7827b5de088b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestones', sa.Column('amount_kobo', sa.Integer(), nullable=False))
    op.drop_column('milestones', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestones', sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('milestones', 'amount_kobo')
    # ### end Alembic commands ###
