"""rename payment_evidence_public_id to plural

Revision ID: 7549a15ad515
Revises: 07a1c0cf6bb9
Create Date: 2026-03-27 07:43:44.455586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7549a15ad515'
down_revision: Union[str, Sequence[str], None] = '07a1c0cf6bb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('harvest_reports', sa.Column('payment_evidence_public_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('harvest_reports', 'payment_evidence_public_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('harvest_reports', sa.Column('payment_evidence_public_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('harvest_reports', 'payment_evidence_public_ids')
    # ### end Alembic commands ###
