"""initial_kobo_schema

Revision ID: 7827b5de088b
Revises: 
Create Date: 2026-03-26 04:19:45.143893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7827b5de088b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_references',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('local_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('growing_months_min', sa.Integer(), nullable=False),
    sa.Column('growing_months_max', sa.Integer(), nullable=False),
    sa.Column('cost_per_hectare_min_kobo', sa.Integer(), nullable=False),
    sa.Column('cost_per_hectare_max_kobo', sa.Integer(), nullable=False),
    sa.Column('yield_per_hectare_min', sa.Float(), nullable=False),
    sa.Column('yield_per_hectare_max', sa.Float(), nullable=False),
    sa.Column('market_price_min_kobo', sa.Integer(), nullable=False),
    sa.Column('market_price_max_kobo', sa.Integer(), nullable=False),
    sa.Column('max_return_rate', sa.Float(), nullable=False),
    sa.Column('max_budget_deviation', sa.Float(), nullable=False),
    sa.Column('max_yield_deviation', sa.Float(), nullable=False),
    sa.Column('min_farm_size_ha', sa.Float(), nullable=False),
    sa.Column('max_farm_size_ha', sa.Float(), nullable=False),
    sa.Column('suitable_states', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('default_milestones', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farmer_id', sa.Uuid(), nullable=False),
    sa.Column('crop_reference_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('crop_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lga', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('farm_size_ha', sa.Float(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_budget_kobo', sa.Integer(), nullable=False),
    sa.Column('amount_raised_kobo', sa.Integer(), nullable=False),
    sa.Column('expected_yield', sa.Float(), nullable=False),
    sa.Column('sale_price_per_unit_kobo', sa.Integer(), nullable=False),
    sa.Column('return_rate', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('harvest_date', sa.Date(), nullable=False),
    sa.Column('farm_status', sa.Enum('DRAFT', 'PENDING', 'ACTIVE', 'FUNDED', 'COMPLETED', 'PAID_OUT', 'REJECTED', 'DEADLINE_PASSED', 'CANCELLED', name='farmstatus'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_verified', sa.Boolean(), nullable=False),
    sa.Column('location_photo_public_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('display_photos_public_id', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confirmed_sales_amount_kobo', sa.Integer(), nullable=True),
    sa.Column('deadline_passed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('extension_decision_deadline', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('extension_count', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crop_reference_id'], ['crop_references.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farms_crop_reference_id'), 'farms', ['crop_reference_id'], unique=False)
    op.create_index(op.f('ix_farms_farmer_id'), 'farms', ['farmer_id'], unique=False)
    op.create_table('harvest_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('farmer_id', sa.Uuid(), nullable=False),
    sa.Column('actual_yield', sa.Float(), nullable=False),
    sa.Column('total_sales_declared_kobo', sa.Integer(), nullable=False),
    sa.Column('harvest_date', sa.Date(), nullable=False),
    sa.Column('buyer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payment_evidence_public_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('admin_confirmed_sales_kobo', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'VERIFIED', 'REJECTED', name='harvestreportstatus'), nullable=False),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id')
    )
    op.create_table('investments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('investor_id', sa.Uuid(), nullable=False),
    sa.Column('amount_kobo', sa.Integer(), nullable=False),
    sa.Column('txn_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('interswitch_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'REFUNDED', 'FAILED', name='investmentstatus'), nullable=False),
    sa.Column('failure_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['investor_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investments_farm_id'), 'investments', ['farm_id'], unique=False)
    op.create_index(op.f('ix_investments_investor_id'), 'investments', ['investor_id'], unique=False)
    op.create_index(op.f('ix_investments_txn_ref'), 'investments', ['txn_ref'], unique=True)
    op.create_table('milestones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.Column('expected_week', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('LOCKED', 'PENDING_PROOF', 'UNDER_REVIEW', 'VERIFIED', 'DISBURSED', 'REJECTED', name='milestonestatus'), nullable=False),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milestones_farm_id'), 'milestones', ['farm_id'], unique=False)
    op.create_table('payouts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_type', sa.Enum('INVESTOR', 'FARMER', name='recipienttype'), nullable=False),
    sa.Column('investment_id', sa.Uuid(), nullable=True),
    sa.Column('principal_kobo', sa.Integer(), nullable=False),
    sa.Column('profit_kobo', sa.Integer(), nullable=False),
    sa.Column('total_amount_kobo', sa.Integer(), nullable=False),
    sa.Column('interswitch_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('WAITING', 'PROCESSING', 'COMPLETED', 'FAILED', name='payoutstatus'), nullable=False),
    sa.Column('failure_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('initiated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payouts_farm_id'), 'payouts', ['farm_id'], unique=False)
    op.create_table('proofs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('milestone_id', sa.Uuid(), nullable=False),
    sa.Column('farmer_id', sa.Uuid(), nullable=False),
    sa.Column('photo_public_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gps_latitude', sa.Float(), nullable=False),
    sa.Column('gps_longitude', sa.Float(), nullable=False),
    sa.Column('gps_accuracy_m', sa.Float(), nullable=True),
    sa.Column('gps_distance_km', sa.Float(), nullable=False),
    sa.Column('gps_flag', sa.Enum('PASS', 'WARNING', 'FAIL', name='gpsflag'), nullable=False),
    sa.Column('gps_flag_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'APPROVED', 'REJECTED', name='proofstatus'), nullable=False),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proofs_milestone_id'), 'proofs', ['milestone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proofs_milestone_id'), table_name='proofs')
    op.drop_table('proofs')
    op.drop_index(op.f('ix_payouts_farm_id'), table_name='payouts')
    op.drop_table('payouts')
    op.drop_index(op.f('ix_milestones_farm_id'), table_name='milestones')
    op.drop_table('milestones')
    op.drop_index(op.f('ix_investments_txn_ref'), table_name='investments')
    op.drop_index(op.f('ix_investments_investor_id'), table_name='investments')
    op.drop_index(op.f('ix_investments_farm_id'), table_name='investments')
    op.drop_table('investments')
    op.drop_table('harvest_reports')
    op.drop_index(op.f('ix_farms_farmer_id'), table_name='farms')
    op.drop_index(op.f('ix_farms_crop_reference_id'), table_name='farms')
    op.drop_table('farms')
    op.drop_table('crop_references')
    # ### end Alembic commands ###
