"""changed initial farm status to draft

Revision ID: 9f05b30dad35
Revises: 2209f290227f
Create Date: 2026-03-25 03:59:51.481073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9f05b30dad35'
down_revision: Union[str, Sequence[str], None] = '2209f290227f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE farmstatus ADD VALUE IF NOT EXISTS 'DRAFT'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE farms SET farm_status = 'PENDING' WHERE farm_status = 'DRAFT'")
    op.execute("ALTER TYPE farmstatus RENAME TO farmstatus_old")
    op.execute("CREATE TYPE farmstatus AS ENUM ('PENDING', 'ACTIVE', 'FUNDED', 'COMPLETED', 'PAID_OUT', 'REJECTED', 'DEADLINE_PASSED', 'CANCELLED')")
    op.execute("ALTER TABLE farms ALTER COLUMN farm_status TYPE farmstatus USING farm_status::text::farmstatus")
    op.execute("DROP TYPE farmstatus_old")
    # ### end Alembic commands ###
