"""add missing repayment fields and fix harvest report typo

Revision ID: a5bfd53f3659
Revises: 7549a15ad515
Create Date: 2026-03-27 08:05:50.000722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a5bfd53f3659'
down_revision: Union[str, Sequence[str], None] = '7549a15ad515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('harvest_reports', sa.Column('payment_evidence_public_id', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('harvest_reports', 'payment_evidence_public_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('harvest_reports', sa.Column('payment_evidence_public_ids', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('harvest_reports', 'payment_evidence_public_id')
    # ### end Alembic commands ###
